services:
  nginx:
    networks:
      - course_papers
    hostname: proxy
    container_name: proxy
    build:
      context: ./nginx
      args:
        - BACKEND_HOST_IP
    environment:
      - BACKEND_HOST_IP
    ports:
      - 80:80
  course_papers_backend:
    hostname: backend
    networks:
      - course_papers
    container_name: course_papers
    build:
      context: ./src/backend
    ports:
      - 8000:8000
  course_papers_web:
    hostname: frontend
    env_file:
      - ./src/web/.env
    environment:
      - BACKEND_HOST_IP=proxy
    networks:
      - course_papers
    container_name: course_papers_web
    build:
      context: ./src/web
    ports:
      - 3000:3000
  
networks:
  course_papers:
    driver: bridge