# Generated by Django 5.0.4 on 2024-05-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePaperModel',
            fields=[
                ('course_paper_id', models.UUIDField(primary_key=True, serialize=False)),
                ('course_paper_name', models.CharField(max_length=100)),
                ('course_paper_student_id', models.UUIDField()),
                ('course_paper_created_at', models.DateTimeField()),
                ('course_paper_current_stage', models.CharField(choices=[('PREPARING', 'PREPARING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ON_REVIEW', 'ON_REVIEW'), ('REVIEWED', 'REVIEWED'), ('BEING_FIXED', 'BEING_FIXED'), ('COMPLETED', 'COMPLETED')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='StageModel',
            fields=[
                ('stage_id', models.UUIDField(primary_key=True, serialize=False)),
                ('stage_name', models.CharField(choices=[('PREPARING', 'PREPARING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ON_REVIEW', 'ON_REVIEW'), ('REVIEWED', 'REVIEWED'), ('BEING_FIXED', 'BEING_FIXED'), ('COMPLETED', 'COMPLETED')], max_length=12)),
                ('stage_created_at', models.DateTimeField()),
                ('stage_course_paper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applications.coursepapermodel')),
            ],
        ),
    ]
